### ISSUE TITLE
Style layer

### ISSUE THREAD

**Issue by darkat** [socib/Leaflet.TimeDimension#8]
Hi,
In example 6, the layer is smoothing (areafill style)
Example 1: contour lines
I have found that there are other filters for ncWMS. How I can install these filters in Thredds? Only exist in the file ImageProducer.java "BOXFILL, VECTOR, CONTOUR, BARB, STUMPVEC, TRIVEC, LINEVEC, FANCYVEC, PRETTYVEC"
Thanks

**Comment by carhonte** [comment]
You may need to modify some source code (.java) to include the news styles,
build and deploy a news war. 
How to include these two styles? I do not know

**Comment by joanpau** [comment]
ncWMS **does not have** a plug-in architecture to extend/modify the available map styles.
The only way to add new styles is to modify the Java source code, compile it,
and use the resulting jar to replace the original version of the library in the Thredds deployment
(and update the involved JSP templates if needed).
Please note that you **do not need** to recompile or deploy a new Thredds war.
Simply updating the ncWMS .jar in `thredds/WEB_INF/lib` is enough
(and the templates in `thredds/WEB_INF/jsp/wms` if needed).

The styles you see in the examples come from the modifications at [socib/ncWMS@pixel_map_rendering_hack][1].
The original reason was the very slow performance when dealing with non orthogonal grids
(so called curvilinear in the code). The solution required to switch to a different approach
to data loading and plotting, since both stages are tightly coupled in the original design.
This opened up the room to improve some of the existing styles (`contour`)
and add new ones (`areafill` and `shadefill`). Some dependencies were removed, too (SGT).

However, these changes **have not been** pull-requested because they rely
on a really tricky (ugly) hack to change the data loading approach.
Also, even though the performance on non-orthogonal grids is (drastically) improved,
it is lowered on orthogonal (rectangular) ones. The reduction is noticeable
on really large or dense grids, although not down to the point of unusability
(like in the case of curvilinear grids in the original code).

The [commit log of the branch][2] contains a detailed explanation of the whole issue
and the new functionality (starting from socib/ncWMS@1c428a55fdf0bcb9ace5ed8955d1770fe2a68a60).
Feel free to use it, but please note that even though it is supposed to work decently
(it is used in production in the organization as you have seen),
it is not supported nor maintained as part of the Thredds or ncWMS projects.

  [1]: https://github.com/socib/ncWMS/tree/pixel_map_rendering_hack
  [2]: https://github.com/socib/ncWMS/commits/pixel_map_rendering_hack

**Comment by darkat** [comment]
Thanks!, it works perfect

**Comment by bielfrontera** [comment]
Ok. Then, I will close this issue. 
@joanpau thanks for your comment  :+1:

**Comment by rsignell-usgs** [comment]
I tried building branch with netbeans and got a bunch of errors like:
```
Compiling 187 source files to C:\Users\rsignell\Documents\GitHub\ncWMS\build\web\WEB-INF\classes
warning: [options] bootstrap class path not set in conjunction with -source 1.6
C:\Users\rsignell\Documents\GitHub\ncWMS\src\java\uk\ac\rdg\resc\edal\cdm\CdmUtils.java:73: error: package ucar.nc2.time does not exist
import ucar.nc2.time.CalendarDate;
C:\Users\rsignell\Documents\GitHub\ncWMS\src\java\uk\ac\rdg\resc\ncwms\config\Config.java:46: error: package javax.servlet does not exist
import javax.servlet.ServletContext;
C:\Users\rsignell\Documents\GitHub\ncWMS\src\java\uk\ac\rdg\resc\ncwms\controller\ServerConfig.java:33: error: package javax.servlet does not exist
import javax.servlet.ServletContext;
C:\Users\rsignell\Documents\GitHub\ncWMS\src\java\uk\ac\rdg\resc\ncwms\config\NcwmsCredentialsProvider.java:40: error: cannot find symbol
import ucar.nc2.util.net.HTTPSession;
  symbol:   class HTTPSession
  location: package ucar.nc2.util.net
C:\Users\rsignell\Documents\GitHub\ncWMS\src\java\uk\ac\rdg\resc\ncwms\config\Config.java:538: error: cannot find symbol
    public File getPaletteFilesLocation(ServletContext context) {
  symbol:   class ServletContext
  location: class Config
```
Obviously I don't know what I'm doing -- I'm just monkey here. 
Are there build instructions or is there a .jar file lying around somewhere?

**Comment by rsignell-usgs** [comment]
Okay, I got help from somebody that knew what they were doing.  :smile_cat: 
```
git clone https://github.com/socib/ncWMS.git
git checkout pixel_map_rendering_hack
mvn -DskipTests=true package
```
worked like a champ.

**Comment by rsignell-usgs** [comment]
But dang it, it didn't work with our TDS 4.6.4 instance.   I removed the old ncWMS.jar, added the newly built one, and changed the `./webapps/thredds/WEB-INF/jsp/wms/*.jsp` files to the ones from the branch, but when I tried a getCaps request, I got back:
```
 java.lang.IllegalArgumentException: The calendar system proleptic_gregorian cannot be handled
```
What do I need to do to fix this?
I'd definitely like to try this branch out, as all our model output is curvilinear!

**Comment by joanpau** [comment]
@rsignell-usgs could you post a link to an example of failing dataset?
And also, could you check if the original ncwms works with that dataset?
This might not be the best place for that ncwms problem.
If we can solve it briefly let's keep on here, otherwise we should probably move to the mail
to not disturb other people lookilng at the leaflet.TimeDimension.

**Comment by joanpau** [comment]
Upstream changes has been merged into the pixel_map_rendering_hack (socib/ncWMS@09b9b072) and this seems to solve the problem.

**Comment by rsignell-usgs** [comment]
Indeed, I pulled the new version, and it works!
http://geoport-dev.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?service=WMS&version=1.3.0&request=GetCapabilities

**Comment by Khamirak** [comment]
Hi dears @rsignell-usgs @joanpau @darkat 
I installed Thredds 4.6.14 in Tomcat servlet and for this purpose I've downloaded   [https://github.com/socib/ncWMS/tree/pixel_map_rendering_hack](NCWMS_pixel_hack)and replaced **/lib/*.jar** files with those in the **thredds##4.6.14/WEB-INF/lib/**. But **areafill** didn't appear yet in GODIVA2.
How do you guys solve your problem?

**Comment by bielfrontera** [comment]
Hi @Khamirak,
these are the steps to replace ncwms by our modified version:
- Download this branch: https://github.com/socib/ncWMS/tree/run_socib_4.6.14
- Compile the code using `mvn package` (you'll get a new ncwms jar)
- At your THREDDS installation, replace WEB-INF/lib/ncwms-1.2.tds.4.6.14.jar by the new jar (you can remove the old jar and add the new one with a different name, for example ncwms-1.2.socib.tds.4.6.14.jar)
- At your THREDDS installation, replace the following jsp files by the files you'd find in our repository at web/WEB-INF/jsp:
  - WEB-INF/jsp/wms/capabilities_xml_1_1_1.jsp
  - WEB-INF/jsp/wms/capabilities_xml.jsp
  - WEB-INF/jsp/wms/showLayerDetails.jsp

Hope this helps!

**Comment by Khamirak** [comment]
Thanks for your reply Biel, @bielfrontera 
It work in GODIVA2 finely but when I use that using wms in javascript the following error released.
`http://localhost:8080/thredds/wms/testAll/newx.nc?service=WMS&request=GetMap&layers=u10&styles=areafill%2Fscb_bugnylorrd&format=image%2Fpng&transparent=true&version=1.1.1&colorscalerange=-2.017%2C2.147&abovemaxcolor=extend&belowmincolor=extend&numcolorbands=250&width=256&height=256&srs=EPSG%3A3857&bbox=-20037508.342789244,-10018754.171394622,-10018754.171394622,0`

> <ServiceExceptionReport version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
> <ServiceException>
> Unexpected error of type java.lang.IllegalArgumentException
> </ServiceException>
> <StackTrace>
> uk.ac.rdg.resc.ncwms.graphics.ColorPalette.get(ColorPalette.java:171)uk.ac.rdg.resc.ncwms.controller.AbstractWmsController.getMap(AbstractWmsController.java:466)thredds.server.wms.ThreddsWmsController.dispatchWmsRequest(ThreddsWmsController.java:179)uk.ac.rdg.resc.ncwms.controller.AbstractWmsController.handleRequestInternal(AbstractWmsController.java:193)org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:174)org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)javax.servlet.http.HttpServlet.service(HttpServlet.java:626)org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)javax.servlet.http.HttpServlet.service(HttpServlet.java:733)org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)thredds.servlet.filter.RequestQueryFilter.doFilter(RequestQueryFilter.java:118)org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)thredds.servlet.filter.RequestCORSFilter.doFilterInternal(RequestCORSFilter.java:49)org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)thredds.servlet.filter.RequestPathFilter.doFilter(RequestPathFilter.java:94)org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)thredds.server.RequestBracketingLogMessageFilter.doFilter(RequestBracketingLogMessageFilter.java:81)org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)java.lang.Thread.run(Thread.java:748)
> </StackTrace>
> </ServiceExceptionReport>



In the final step when I want to see wms the following error release:
`http://localhost:8080/thredds/wms/testAll/newx.nc?service=WMS&version=1.3.0&request=GetCapabilities
`

> HTTP Status 500 - Internal Server Error
> 
> Status 500 - Internal Server Error
> THREDDS Data Server Version 4.6 -- Documentation  


You think how could I solve this?

**Comment by bielfrontera** [comment]
The `IllegalArgumentException` is raised because it does not find the palette `scb_bugnylorrd` in your system (they are located at WEB-INF/palettes). 

And in order to know why the GetCapabilites request is not working, you should check the server log (without any hint, i cannot help).

**Comment by Khamirak** [comment]
Hi again @bielfrontera
My first question about palette has been solved.
Although I've tried to solve my problem, but issue was remained. I want to see wms GetCapabilities the following error release:
http://localhost:8080/thredds/wms/testAll/newx.nc?service=WMS&version=1.3.0&request=GetCapabilities

HTTP Status 500 - Internal Server Error

Status 500 - Internal Server Error
THREDDS Data Server Version 4.6 -- Documentation

I attached my log folder.
You think what is the problem?
[logs.zip](https://github.com/socib/Leaflet.TimeDimension/files/5176763/logs.zip)
.
